FinalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("portal/", include("portal.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("at-a-glance", views.AtAGlanceView.as_view(), name="at_a_glance"),
    path("facts", views.FactsView.as_view(), name="facts"),
    path('vision-and-mission', views.VisionMissionView.as_view(), name="vision_and_mission"),
    path("special-initiatives", views.SpecialInitiativesView.as_view(), name="special_initiatives"),
    path('leadership', views.LeadershipView.as_view(), name="leadership"),
    path("about-us-message", views.AboutUsView.as_view(), name="about_us"),
    path("research", views.ResearchView.as_view(), name="research"),
    path("contact-us", views.ContactView.as_view(), name="contact")
]

portal/urls.py
from django.urls import path
from . import views

app_name = "portal"

urlpatterns = [
    path("", views.redirect_view, name="home"),
    path("login", views.LoginView.as_view(), name="login"),
    path("dashboard", views.DashboardView.as_view(), name="dashboard"),
    path("course-registration-and-add-drop", views.CourseRegistrationAddDropView.as_view(), name="registration_add_drop"),
    path("registration-bill", views.RegistrationBillView.as_view(), name="registration_bill"),
    path("course-withdrawal", views.CourseWithdrawalView.as_view(), name="course_withdrawal"),
    path("submit-application", views.SubmitApplicationView.as_view(), name="submit_application"),
    path("new-application", views.NewApplicationView.as_view(), name="new_application"),
    path("profile", views.ProfileView.as_view(), name="profile"),
    path("logout", views.logout_view, name="logout"),
    path("faculty-evaluation", views.FacultyEvaluationView.as_view(), name="faculty_evaluation"),
    path("student-admission", views.StudentAdmissionView.as_view(), name="admission")
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator


class User(AbstractUser):
    photo = models.ImageField(upload_to="user_photos")
    user_id = models.CharField(max_length=10, unique=True)
    
    BLOOD_GROUP_CHOICES = (
        ("A+", "A+"),
        ("A-", "A-"),
        ("B+", "B+"),
        ("B-", "B-"),
        ("AB+", "AB+"),
        ("AB-", "AB-"),
        ("O+", "O+"),
        ("O-", "O-")
    )
    
    blood_group = models.CharField(max_length=4, choices=BLOOD_GROUP_CHOICES)
    
    present_address = models.TextField()
    permanent_address = models.TextField()

    
    # emergency contact
    
    # financial guarantor
    
    # o,alevel certificate
    
    
class StudentGuardian(models.Model):
    student = models.ManyToManyField(User)
    full_name = models.CharField(max_length=300)
    relation = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    profession = models.CharField(max_length=200, blank=True)
    
    def __str__(self):
        return f"Guardian - {self.full_name}"
    
    
class EmergencyContact(models.Model):
    student = models.ManyToManyField(User)
    full_name = models.CharField(max_length=300)
    relation = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    profession = models.CharField(max_length=200, blank=True)
    
    def __str__(self):
        return f"Emergency Contact - {self.full_name}"
    

class FinancialGuarantor(models.Model):
    student = models.ManyToManyField(User)
    full_name = models.CharField(max_length=300)
    relation = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    profession = models.CharField(max_length=200, blank=True)
    approximate_yearly_income = models.FloatField(validators=[MinValueValidator(50000)])
    
    def __str__(self):
        return f"Financial Guarantor - {self.full_name}"


class Course(models.Model):
    course_code = models.CharField(max_length=8)
    course_title = models.CharField(max_length=300)
    pre_requisite = models.ManyToManyField("Course", related_name="successor_courses", blank=True)
    COURSE_TYPE_CHOICES = (
        ("MAJ", "Major"),
        ("MIN", "Minor"),
        ("COR", "Core"),
        ("OPT", "Optional"),
        ("FOU", "Foundation")
    )
    course_type = models.CharField(max_length=3, choices=COURSE_TYPE_CHOICES)
    
    def __str__(self):
        return f"{self.course_code} - {self.course_title}"
    
    
class CourseSection(models.Model):
    course = models.OneToOneField(Course, on_delete=models.CASCADE)
    section_number = models.IntegerField(validators=[MinValueValidator(1)])
    instructor = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    time_start = models.TimeField()
    time_end = models.TimeField()
    WEEKDAY_CHOICES = (
        ("ST", "Sunday & Tuesday"),
        ("MW", "Monday & Wednesday"),
        ("AR", "Thursday & Saturday")
    )
    # weekdays
    
    def __str__(self):
        return f"{self.course} - {self.section_number}"
    
    def get_course_timing_as_str(self):
        return f"Monday & Wednesday {self.time_start.strftime('%I:%M %p')} - {self.time_end.strftime('%I:%M %p')}"
    

class EnrolledCourse(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course_section = models.ForeignKey(CourseSection, on_delete=models.CASCADE)
    num_classes_taken = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    num_classes_attended = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    
    GRADE_CHOICES = (
        ("A", "A"),
        ("A-", "A-"),
        ("B+", "B+"),
        ("B", "B"),
        ("B-", "B-"),
        ("C+", "C+"),
        ("C", "C"),
        ("C-", "C-"),
        ("D+", "D+"),
        ("D", "D"),
        ("D-", "D-"),
        ("F", "F"),
        ("I", "I"),
        ("W", "W"),
        ("Z", "Z")
    )
    
    grade = models.CharField(max_length=3, choices=GRADE_CHOICES, default="Z")
    
    GRADE_POINTS = {
        "A": 4.0,
        "A-": 3.75,
        "B+": 3.5,
        "B": 3.25,
        "B-": 3.0,
        "C+": 2.75,
        "C": 2.5,
        "C-": 2.0,
        "D+": 1.75,
        "D": 1.5,
        "D-": 1.0
    }
    
    def __str__(self):
        return f"{self.student} - {self.course_section}"

main/views.py
from django.shortcuts import render
from django.views import generic


class IndexView(generic.View):
    template_name = "main/index.html"
    
    def get(self, request):
        return render(request, self.template_name)
    
    
class AtAGlanceView(generic.View):
    template_name = "main/at_a_glance.html"
    
    def get(self, request):
        return render(request, self.template_name)


class FactsView(generic.View):
    template_name = "main/facts.html"
    
    def get(self, request):
        return render(request, self.template_name)


class VisionMissionView(generic.View):
    template_name = "main/vision_mission.html"
    
    def get(self, request):
        return render(request, self.template_name)


class SpecialInitiativesView(generic.View):
    template_name = "main/special.html"
    
    def get(self, request):
        return render(request, self.template_name)
    
    
class LeadershipView(generic.View):
    template_name = "main/leadership.html"
    
    def get(self, request):
        return render(request, self.template_name)
    
    
class AboutUsView(generic.View):
    template_name = "main/about_us.html"
    
    def get(self, request):
        return render(request, self.template_name)
    
    
class ResearchView(generic.View):
    template_name = "main/research.html"
    
    def get(self, request):
        return render(request, self.template_name)
    
    
class ContactView(generic.View):
    template_name = "main/contact.html"
    
    def get(self, request):
        return render(request, self.template_name)

templates/main/about_us.html
{% extends 'main/base.html' %}
{% block title %}Message from the Vice Chancellor {% endblock %}

{% load static %}
{% block style %}
    <link type="text/css" rel="stylesheet" href="{% static 'main/about_us.css' %}">
{% endblock %}

{% block body %}
    <section id="aboutus">
        <div class="rowa">
            <div class="col1">
                <div class="imgchange">
                    <img src="https://www.monash.edu/__data/assets/image/0008/3531095/Professor-Sharon-Pickering-profile.jpg" alt="Prof. Sharon Pickering" class="img1" >
                </div>
                    
            </div>
            <div class="col2">
                <h2>Prof. Sharon Pickering</h2>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                    It has survived not only five centuries, but also the leap into electronic typesetting, remaining 
                    essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing 
                    Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including 
                    versions of Lorem Ipsum.</p>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                    It has survived not only five centuries, but also the leap into electronic typesetting, remaining 
                    essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing 
                    Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including 
                    versions of Lorem Ipsum.</p>
                
                
            </div>
        </div>
    </section>
{% endblock %}

templates/main/at_a_glance.html
{% extends 'main/base.html' %}

{% block title %}Sagacity Education At A Glance{% endblock %}

{% load static %}
{% block style %}
    <link type="text/css" rel="stylesheet" href="{% static 'main/at_a_glance.css' %}">
{% endblock %}

{% block body %}
     <section>
        <div class="row1">
            <div class="add">
                <img src="https://www.usnews.com/object/image/00000189-30bd-d6f6-a99b-ffbd1f840000/gettyimages-1478520911.jpg?update-time=1688739913761&size=responsive640" alt="" height="350px" width="550px" class="img1">
                <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. <br>Possimus consequuntur ab accusamus earum modi provident.</h3>
            <p>Jan 11,2021</p>
            </div>
            
            <div class="add1">
                <img src="https://www.uh.edu/_images/_homepage/banner-mobile.jpg" alt="" height="350px" width="550px" class="img2">
                <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. <br>Possimus consequuntur ab accusamus earum modi provident.</h3>
                <p>Jan 11,2021</p>
            </div>
        </div>
        <div class="row2">
            <div class="addd">
                <img src="https://www.universitiesuk.ac.uk/sites/default/files/styles/content_banner_on_desktop/public/image-upload/getti/students-AdobeStock_428930939.jpeg?h=5cce16ed&itok=YS4W1rsp" alt="" height="300px" width="500px" class="img11">
                <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. <br>Possimus consequuntur ab accusamus earum modi provident.</h3>
            <p>Jan 11,2021</p>
            </div>
            
            <div class="add11">
                <img src="https://b1806469.smushcdn.com/1806469/wp-content/uploads/2024/05/AUGraduation2024-670.jpg?lossy=2&strip=1&webp=1" alt="" height="350px" width="550px" class="img21">
                <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. <br>Possimus consequuntur ab accusamus earum modi provident.</h3>
                <p>Jan 11,2021</p>
            </div>
        </div>

    </section>
    <section id="ban">
        <div class="banner">
            <h4>Discover. Learn. Grow. Achieve.</h4>
            <h1>Empowering Minds Through Education</h1>
            <button class="but">Learn More</button>
        </div>
    </section>
    <section>
        <div class="row1">
            <div class="add">
                <img src="https://www.makehappen.org/wp-content/uploads/2020/04/600-campus-75731374.jpg" alt="" height="300px" width="500px" class="img1">
                <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. <br>Possimus consequuntur ab accusamus earum modi provident.</h3>
            <p>Jan 11,2021</p>
            </div>
            
            <div class="add1">
                <img src="https://media.istockphoto.com/id/1458679553/photo/group-of-high-school-students-using-laptop-in-library.jpg?s=612x612&w=0&k=20&c=J3m3dun5n8O8upIbOZ_nqFG1K4EBFqh0MYonPgMfm5g=" alt="" height="350px" width="550px" class="img2">
                <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. <br>Possimus consequuntur ab accusamus earum modi provident.</h3>
                <p>Jan 11,2021</p>
            </div>
        </div>
        <div class="row2">
            <div class="addd">
                <img src="https://publish.purewow.net/wp-content/uploads/sites/2/2017/08/suzzallo-library-at-the-university-of-washington.jpg?fit=728%2C524" alt="" height="380px" width="550px" class="img11">
                <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. <br>Possimus consequuntur ab accusamus earum modi provident.</h3>
            <p>Jan 11,2021</p>
            </div>
            
            <div class="add11">
                <img src="https://media.globaladmissions.com/media/asset/2024/12/9411186a420349cc873732ee4b1f1d2c.jpg" alt="" height="360px" width="580px" class="img21">
                <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. <br>Possimus consequuntur ab accusamus earum modi provident.</h3>
                <p>Jan 11,2021</p>
            </div>
        </div>

    </section>
{% endblock %}

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Inter font from Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" xintegrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Fontawesome link for icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% load static %}
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/base.css' %}">
    {% block style %}{% endblock %}

</head>
<body>

    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="https://placehold.co/40x40/007bff/ffffff?text=U" alt="University Logo" class="rounded-circle me-2">
                    Sagacity Education
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item dropdown-custom">
                            <a class="nav-link" href="#">About Us</a>
                            <ul class="dropdown-menu-custom">
                                <li><a href="{% url 'main:at_a_glance' %}">Sagacity at a Glance</a></li>
                                <li><a href="{% url 'main:vision_and_mission' %}">Vision &amp; Mission</a></li>
                                <li><a href="{% url 'main:facts' %}">Facts &amp; Figures</a></li>
                                <li><a href="{% url 'main:special_initiatives' %}">Special Initiatives</a></li>
                                <li><a href="{% url 'main:leadership' %}">Leadership &amp; Governance</a></li>
                                <li><a href="{% url 'main:about_us' %}">Message from the Vice Chancellor</a></li>
                            </ul>
                            </li>
                        <li class="nav-item dropdown-custom">
                            <a class="nav-link" href="#">Academics</a>
                            <ul class="dropdown-menu-custom">
                                <li><a href="#">Undergraduate Programs</a></li>
                                <li><a href="#">Graduate Programs</a></li>
                                <li><a href="#">Schools</a></li>
                                <li><a href="#">Departments</a></li>
                                <li><a href="#">Institutes, Centers &amp; Cells</a></li>
                                <li><a href="#">Institutional Quality Assurance Cell (IQAC)</a></li>
                                <li><a href="#">Outreach Extension &amp; Continuing Education (OECE)</a></li>
                                <li><a href="#">Library</a></li>
                            </ul>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'portal:admission' %}">Admissions</a>
                        </li>
                        <li class="nav-item dropdown-custom">
                            <a class="nav-link" href="#">Research</a>
                            <ul class="dropdown-menu-custom">
                                <li><a href="{% url 'main:research' %}">Research at Sagacity Education</a></li>
                                <li><a href="#">Sagacity Sponsored Research Projects</a></li>
                                <li><a href="#">Publications</a></li>
                                <li><a href="#">Centers for Research</a></li>
                                <li><a href="#">Academic Repository</a></li>
                            </ul>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'portal:dashboard' %}">Portal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    {% block body %}
    {% endblock %}

    <!-- Footer -->
    <footer class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-3 mb-md-0">
                    <h5>Quick Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="/portal/student-admission">Admissions</a></li>
                        <li><a href="#">Academics</a></li>
                        <li><a href="#">Library</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="col-md-4 mb-3 mb-md-0">
                    <h5>Contact Us</h5>
                    <p>123 University Ave, City, Country</p>
                    <p>Email: info@university.edu</p>
                    <p>Phone: +1 (123) 456-7890</p>
                </div>
                <div class="col-md-4">
                    <h5>Follow Us</h5>
                    <a href="#" class="text-white me-3"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="text-white me-3"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="text-white me-3"><i class="fab fa-linkedin-in"></i></a>
                    <a href="#" class="text-white"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
            <hr class="my-4">
            <p class="mb-0">&copy; 2025 University Name. All rights reserved.</p>
        </div>
    </footer>

    <!-- Bootstrap JS Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" xintegrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Custom JavaScript -->
    
    <script type="text/javascript" src="{% static 'main/base.js' %}"></script>

    {% block script %}{% endblock %}
</body>
</html>

templates/main/contact.html
{% extends 'main/base.html' %}
{% block title %} Contact Us{% endblock %}

{% load static %}
{% block style %}
    <link href="{% static 'main/contact.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block body %}
    <h1>Contact Us</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut laboriosam voluptatum vitae facilis maiores, amet, eos voluptatibus saepe deserunt nihil nobis explicabo aperiam a consectetur.</p>
    <section class="contactsection">
        <div class="contact">
            <h2>Send Message</h2>
            <div class="mescontact">
                <input type="text" required="required">
                <span>Full name</span>
            </div>
            <div class="mescontact">
                <input type="text" required="required">
                <span>Email</span>
            </div>
            <div class="mescontact">
                <textarea required="required"></textarea>
                <span>Type your Message...</span>
            </div>
            <div class="mescontact">
                <input type="submit" value="Send"></button>
            </div>
        </div>
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3153.123456789012!2d-122.419415684681!3d37.774929779759!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8085809c8b8b8b8b%3A0x8b8b8b8b8b8b8b8b!2sSan%20Francisco%20City%20Hall!5e0!3m2!1sen!2sus!4v1616161616161" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </section>

{% endblock %}

templates/main/facts.html
{% extends 'main/base.html' %}

{% block title %}Sagacity Education - Facts{% endblock %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'main/facts.css' %}">
{% endblock %}

{% block body %}
    <h1 class="text-center my-5">Sagacity Education Facts & Figures</h1>
    <p class="text-center mb-5">Explore the key statistics and achievements of Sagacity Education, showcasing our commitment to excellence in education and research.</p>
    <section>
        <div class="contaienrrr">
        <div class="chart">
            <canvas id="barchart" width="300" height="300"></canvas>
        </div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis voluptatibus voluptates vero, nesciunt dicta omnis quo ab ipsa nisi, dolor quas sed nam eius alias. Quod corporis explicabo quisquam dolore! <br>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur repudiandae officiis, dolorum dolore veniam atque ipsam neque aliquam est eveniet quas in perferendis, provident aliquid asperiores quia facilis dolor laudantium.</p>
        
        <div class="chart">
            <canvas id="doughnut" width="300" height="300"></canvas>
        </div>
    </div>
    </section>
    <h1 class="text-center my-5">Lorem ipsum dolor sit amet</h1>
    <p class="text-center mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis eos non, sint qui expedita, repellendus, amet numquam voluptatum tenetur nulla a. Exercitationem quidem amet unde quibusdam eius, recusandae tenetur? Architecto!
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis eos non, sint qui expedita, repellendus, amet numquam voluptatum tenetur nulla a. Exercitationem quidem amet unde quibusdam eius, recusandae tenetur? Architecto!</p>
    </p>
    <section>
        <div class="contaienrrr1">
        <div class="chart1">
            <canvas id="barchart2" width="300" height="300"></canvas>
        </div>
        
        <div class="chart1">
            <canvas id="barchart3" width="300" height="300"></canvas>
        </div>
    </div>
    </section>
    <h1 class="text-center my-5">Lorem ipsum dolor sit amet</h1>
    <p class="text-center mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis eos non, sint qui expedita, repellendus, amet numquam voluptatum tenetur nulla a. Exercitationem quidem amet unde quibusdam eius, recusandae tenetur? Architecto!
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis eos non, sint qui expedita, repellendus, amet numquam voluptatum tenetur nulla a. Exercitationem quidem amet unde quibusdam eius, recusandae tenetur? Architecto!</p>
    </p>
    <section>
        <div class="contaienrrr">
        <div class="chart">
            <canvas id="barchart1" width="300" height="300"></canvas>
        </div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis voluptatibus voluptates vero, nesciunt dicta omnis quo ab ipsa nisi, dolor quas sed nam eius alias. Quod corporis explicabo quisquam dolore! <br>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur repudiandae officiis, dolorum dolore veniam atque ipsam neque aliquam est eveniet quas in perferendis, provident aliquid asperiores quia facilis dolor laudantium.</p>
        
        <div class="chart">
            <canvas id="Linechart" width="300" height="300"></canvas>
        </div>
    </div>
    </section>
{% endblock %}

{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'main/chart1.js' %}" type="text/javascript"></script>
{% endblock %}

templates/main/research.html
{% extends 'main/base.html' %}

{% block title %}Research at Sagacity Education{% endblock %}

{% load static %}

{% block style %}
    <link type="text/css" rel="stylesheet" href="{% static 'main/research.css' %}">
{% endblock %}

{% block body %}
    <section>
        <div class="informationpart">
            <h1>Research at Sagacity Education</h1>
            <p>At Sagacity Education, we are committed to advancing knowledge and fostering innovation through cutting-edge research. Our research initiatives span various disciplines, aiming to address real-world challenges and contribute to the global academic community.
            We encourage collaboration among faculty, students, and industry partners to create impactful research outcomes. Our state-of-the-art facilities and resources support a vibrant research environment that nurtures creativity and critical thinking.
            Explore our research projects, publications, and centers dedicated to pushing the boundaries of knowledge. Join us in our mission to make a difference through research excellence.</p>
        </div>
        <div class="researchpart">
            <h2>Research Areas</h2>
            <ul>
                <li>Artificial Intelligence and Machine Learning</li>
                <li>Environmental Sustainability</li>
                <li>Health Sciences and Biotechnology</li>
                <li>Social Sciences and Humanities</li>
                <li>Engineering and Technology</li>
            </ul>
        </div>
        <div class="researchpart">
            <h2>Research Centers</h2>
            <ul>
                <li>Center for Artificial Intelligence Research</li>
                <li>Institute for Environmental Studies</li>
                <li>Health Innovation Center</li>
                <li>Social Research Institute</li>
                <li>Engineering and Technology Hub</li>
            </ul>
        </div>
        <div class="buttongroup">
            <button class="res">Explore more</button>
            <button class="res">Read more</button>
        </div>
    </section>
    <section>
        <div class="picsres">
            <div class="pi">
                <img src="https://las.uic.edu/wp-content/uploads/sites/181/2024/07/06-28-24-Donald-Wink-8789-1090x727.jpg" alt="" height="300px" width="400px">
                <img src="https://marvel-b1-cdn.bc0a.com/f00000000297652/eloncdn.blob.core.windows.net/eu3/sites/74/2022/12/10_24_22_Amanda-Chuncos-Wildlife-Ecology-Course_015.jpg" alt="" height="300px" width="400px">
                <img src="https://brocku.ca/brock-news/wp-content/uploads/2025/07/CEWIL-Chemistry-Group-Shot.jpg?x56978" alt="" height="300px" width="400px">
                <img src="https://www.bowdoin.edu/biology/images/student-research-biology.jpg" alt="" height="300px" width="400px">
            </div>
        </div>
    </section>
{% endblock %}